"""make card_number nullable and add pos_code

Revision ID: 26aac93af61f
Revises: f295becdca4e
Create Date: 2026-05-29 19:58:52.051587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26aac93af61f'
down_revision: Union[str, Sequence[str], None] = 'f295becdca4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'card_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # Manually added because autogenerate missed it due to manual DB recreation
    op.add_column('pos_machines', sa.Column('pos_code', sa.String(length=2), nullable=True))
    op.create_index(op.f('ix_pos_machines_pos_code'), 'pos_machines', ['pos_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pos_machines_pos_code'), table_name='pos_machines')
    op.drop_column('pos_machines', 'pos_code')
    op.alter_column('cards', 'card_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
