"""fresh_start

Revision ID: 3c253c7c338f
Revises: 
Create Date: 2026-04-19 22:46:46.479920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c253c7c338f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=100), nullable=False),
    sa.Column('card_uuid', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('customer_uuid', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bound_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_card_number'), 'cards', ['card_number'], unique=True)
    op.create_index(op.f('ix_cards_card_uuid'), 'cards', ['card_uuid'], unique=True)
    op.create_index(op.f('ix_cards_customer_uuid'), 'cards', ['customer_uuid'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_status'), 'cards', ['status'], unique=False)
    op.create_table('pos_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_sn', sa.String(length=16), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_action_logs_id'), 'pos_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_pos_action_logs_pos_sn'), 'pos_action_logs', ['pos_sn'], unique=False)
    op.create_table('pos_machines',
    sa.Column('pos_sn', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('lock_status', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('region_id', sa.String(length=50), nullable=True),
    sa.Column('branch_office', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('pos_sn')
    )
    op.create_index(op.f('ix_pos_machines_pos_sn'), 'pos_machines', ['pos_sn'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('landline', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ice_name', sa.String(), nullable=True),
    sa.Column('ice_phone', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('town_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.create_index(op.f('ix_customers_region_id'), 'customers', ['region_id'], unique=False)
    op.create_index(op.f('ix_customers_uuid'), 'customers', ['uuid'], unique=True)
    op.create_table('global_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_rates_id'), 'global_rates', ['id'], unique=False)
    op.create_table('subsidiaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('region_id')
    )
    op.create_index(op.f('ix_subsidiaries_id'), 'subsidiaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subsidiaries_id'), table_name='subsidiaries')
    op.drop_table('subsidiaries')
    op.drop_index(op.f('ix_global_rates_id'), table_name='global_rates')
    op.drop_table('global_rates')
    op.drop_index(op.f('ix_customers_uuid'), table_name='customers')
    op.drop_index(op.f('ix_customers_region_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_pos_machines_pos_sn'), table_name='pos_machines')
    op.drop_table('pos_machines')
    op.drop_index(op.f('ix_pos_action_logs_pos_sn'), table_name='pos_action_logs')
    op.drop_index(op.f('ix_pos_action_logs_id'), table_name='pos_action_logs')
    op.drop_table('pos_action_logs')
    op.drop_index(op.f('ix_cards_status'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_customer_uuid'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_uuid'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_number'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
