"""fix_solar_unit_uuid_type

Revision ID: f295becdca4e
Revises: 3c253c7c338f
Create Date: 2026-04-20 01:19:36.584672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f295becdca4e'
down_revision: Union[str, Sequence[str], None] = '3c253c7c338f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_entities_id'), table_name='business_entities')
    op.drop_table('business_entities')
    op.drop_index(op.f('ix_solar_units_city'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_customer_uuid'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_equipment_status'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_flashlight_id'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_flashlight_status'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_id'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_led_light_id'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_led_status'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_radio_id'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_radio_status'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_shs_machine_id'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_shs_status'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_solar_equipment_id'), table_name='solar_units')
    op.drop_index(op.f('ix_solar_units_town'), table_name='solar_units')
    op.drop_table('solar_units')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solar_units',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shs_machine_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('solar_equipment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('radio_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('flashlight_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('led_light_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('shs_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('equipment_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('radio_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flashlight_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('led_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_uuid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('town', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('production_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bound_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('solar_units_pkey'))
    )
    op.create_index(op.f('ix_solar_units_town'), 'solar_units', ['town'], unique=False)
    op.create_index(op.f('ix_solar_units_solar_equipment_id'), 'solar_units', ['solar_equipment_id'], unique=True)
    op.create_index(op.f('ix_solar_units_shs_status'), 'solar_units', ['shs_status'], unique=False)
    op.create_index(op.f('ix_solar_units_shs_machine_id'), 'solar_units', ['shs_machine_id'], unique=True)
    op.create_index(op.f('ix_solar_units_radio_status'), 'solar_units', ['radio_status'], unique=False)
    op.create_index(op.f('ix_solar_units_radio_id'), 'solar_units', ['radio_id'], unique=True)
    op.create_index(op.f('ix_solar_units_led_status'), 'solar_units', ['led_status'], unique=False)
    op.create_index(op.f('ix_solar_units_led_light_id'), 'solar_units', ['led_light_id'], unique=True)
    op.create_index(op.f('ix_solar_units_id'), 'solar_units', ['id'], unique=False)
    op.create_index(op.f('ix_solar_units_flashlight_status'), 'solar_units', ['flashlight_status'], unique=False)
    op.create_index(op.f('ix_solar_units_flashlight_id'), 'solar_units', ['flashlight_id'], unique=True)
    op.create_index(op.f('ix_solar_units_equipment_status'), 'solar_units', ['equipment_status'], unique=False)
    op.create_index(op.f('ix_solar_units_customer_uuid'), 'solar_units', ['customer_uuid'], unique=False)
    op.create_index(op.f('ix_solar_units_city'), 'solar_units', ['city'], unique=False)
    op.create_table('business_entities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('business_entities_region_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('business_entities_pkey')),
    sa.UniqueConstraint('name', name=op.f('business_entities_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('region_id', name=op.f('business_entities_region_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_business_entities_id'), 'business_entities', ['id'], unique=False)
    # ### end Alembic commands ###
